### ISSUE TITLE
功能建议：将配置文件放置在其他位置

### ISSUE THREAD

**Issue by alfoil** [Chaoses-Ib/ObsidianShell#3]
配置文件目前在软件安装目录 C:\Program Files\Chaoses Ib\ObsidianShell，修改配置后需要管理员权限才能保存。
希望能修改默认放置在 %userprofile% 或者 %appdata%，方便保存和备份。

另外，能不能出一个 portable 便携版？

**Comment by Chaoses-Ib** [comment]
配置文件之所以放在程序目录，其中一个原因就是为了屏蔽安装版和便携版的区别，但因为手动注册右键菜单不太实际，写代码又要花时间，所以便携版最后搁置了。另外，我理想中的配置方式其实是 GUI 配置，因为 Obsidian 的用户群体主要是普通用户，编辑 XML 虽然不复杂，但也不算友好；但因为一方面用的人不多，另一方面这段时间经济压力很大，所以最后也搁置了。

明天或者后天我会发布 v0.3，修改下安装版的配置路径，再打包个便携版，不过便携版就不会支持注册右键菜单了。

**Comment by alfoil** [comment]
您写的说明文件太简略了，我按自己的理解写了一些打开模式的处理逻辑，您有空看下是否有问题？

![20221105232112](https://user-images.githubusercontent.com/15233248/200127146-f8e0b32f-79cf-4467-8582-2c6a03717c26.png)

**Comment by Chaoses-Ib** [comment]
> 即该 md 文件不属于 Obsidian 的仓库列表中的任何一个仓库

Obsidian 没有提供用来判断一个目录是否在仓库列表中的 API，ObsidianShell 判断文件是否在仓库中依靠的是上级目录是否存在 `.obsidian`，而不是仓库列表。这也是“你必须在之前打开过那个仓库，否则 Obsidian 会报错”的原因。

> 并在 Recent 仓库目录下创建该 md 文件的链接（类似于软链接）

这里创建的应该是 md 文件父目录的链接。

其它地方没什么问题。

**Comment by alfoil** [comment]
OK，感谢~

**Comment by Chaoses-Ib** [comment]
[v0.3](https://github.com/Chaoses-Ib/ObsidianShell/releases/tag/v0.3) 已发布。配置文件现在位于 `%LOCALAPPDATA%\Chaoses Ib\ObsidianShell\ObsidianShell.Config`，由于漫游路径配置可能会导致问题，所以没有使用 `%APPDATA%`。
