### ISSUE TITLE
把文件图标换成obsidian的新logo？

### ISSUE THREAD

**Issue by calmwaves111** [Chaoses-Ib/ObsidianShell#7]
一个没有多大用的小建议，obsidian的新logo已经看习惯了，突然又看到了旧logo一时还有点惊讶

**Comment by Chaoses-Ib** [comment]
[v0.5](https://github.com/Chaoses-Ib/ObsidianShell/releases/tag/v0.5) 已更新。

其实当时看到 Obsidian 说要换图标的消息就想换的，但是用新图标的版本一直没有推送到我这里，后来就搁置了。
